name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build --build-arg NODE_IMAGE=node:14-alpine -t skilledsantoshh/test:hareykrishna_ci_cd .

      - name: Push the Docker image to Docker Hub
        run: docker push skilledsantoshh/test:hareykrishna_ci_cd
